/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MyHeader {
    'fbicon': string;
    'homeUrl': string;
    'icon': string;
    'label': string;
    'open': boolean;
    'thetitle': string;
    'twiticon': string;
    'width': string;
  }
}

declare global {


  interface HTMLMyHeaderElement extends Components.MyHeader, HTMLStencilElement {}
  var HTMLMyHeaderElement: {
    prototype: HTMLMyHeaderElement;
    new (): HTMLMyHeaderElement;
  };
  interface HTMLElementTagNameMap {
    'my-header': HTMLMyHeaderElement;
  }
}

declare namespace LocalJSX {
  interface MyHeader {
    'fbicon'?: string;
    'homeUrl'?: string;
    'icon'?: string;
    'label'?: string;
    'onActive'?: (event: CustomEvent<any>) => void;
    'onOnToggle'?: (event: CustomEvent<any>) => void;
    'open'?: boolean;
    'thetitle'?: string;
    'twiticon'?: string;
    'width'?: string;
  }

  interface IntrinsicElements {
    'my-header': MyHeader;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'my-header': LocalJSX.MyHeader & JSXBase.HTMLAttributes<HTMLMyHeaderElement>;
    }
  }
}


