/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface InteraktifHomeHeader {
    'homeIcon': string;
    'homeUrl': string;
    'theTitle': string;
  }
  interface MyHeader {
    'fbIcon': string;
    'homeIcon': string;
    'homeUrl': string;
    'theTitle': string;
    'twitIcon': string;
  }
}

declare global {


  interface HTMLInteraktifHomeHeaderElement extends Components.InteraktifHomeHeader, HTMLStencilElement {}
  var HTMLInteraktifHomeHeaderElement: {
    prototype: HTMLInteraktifHomeHeaderElement;
    new (): HTMLInteraktifHomeHeaderElement;
  };

  interface HTMLMyHeaderElement extends Components.MyHeader, HTMLStencilElement {}
  var HTMLMyHeaderElement: {
    prototype: HTMLMyHeaderElement;
    new (): HTMLMyHeaderElement;
  };
  interface HTMLElementTagNameMap {
    'interaktif-home-header': HTMLInteraktifHomeHeaderElement;
    'my-header': HTMLMyHeaderElement;
  }
}

declare namespace LocalJSX {
  interface InteraktifHomeHeader {
    'homeIcon'?: string;
    'homeUrl'?: string;
    'theTitle'?: string;
  }
  interface MyHeader {
    'fbIcon'?: string;
    'homeIcon'?: string;
    'homeUrl'?: string;
    'theTitle'?: string;
    'twitIcon'?: string;
  }

  interface IntrinsicElements {
    'interaktif-home-header': InteraktifHomeHeader;
    'my-header': MyHeader;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'interaktif-home-header': LocalJSX.InteraktifHomeHeader & JSXBase.HTMLAttributes<HTMLInteraktifHomeHeaderElement>;
      'my-header': LocalJSX.MyHeader & JSXBase.HTMLAttributes<HTMLMyHeaderElement>;
    }
  }
}


